import { Router } from "express";
import authRoutes from "./auth.js";
import districtRoutes from "./districts.js";
import sensorRoutes from "./sensors.js";
import satelliteRoutes from "./satellite.js";
import alertRoutes from "./alerts.js";
import communityRoutes from "./community.js";
import forecastRoutes from "./forecasts.js";
import dashboardRoutes from "./dashboard.js";
import mapLayerRoutes from "./mapLayers.js";
import developerRoutes from "./developer.js";
import publicApiRoutes from "./publicApi.js";
import simulationRoutes from "./simulations.js";
import advisoryRoutes from "./advisory.js";
import waterSourceRoutes from "./waterSources.js";
import mapRoutes from "./map.js";
import { groundwaterRouter, ndviRouter, rainfallRouter } from "./analytics.js";
import weatherRoutes from "./weather.js";
import reportRoutes from "./reports.js";
import tenantRoutes from "./tenants.js";
import uploadRoutes from "./uploads.js";
import providerSensorRoutes from "./providerSensors.js";
import settingsRoutes from "./settings.js";
import aoiRoutes from "./aois.js";
import { attachTenant } from "../middleware/tenant.js";

const router = Router();

router.use(attachTenant);
router.use("/auth", authRoutes);
router.use("/districts", districtRoutes);
router.use("/sensors", sensorRoutes);
router.use("/satellite", satelliteRoutes);
router.use("/alerts", alertRoutes);
router.use("/community", communityRoutes);
router.use("/forecasts", forecastRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/map-layers", mapLayerRoutes);
router.use("/developer", developerRoutes);
router.use("/public", publicApiRoutes);
router.use("/simulations", simulationRoutes);
router.use("/advisory", advisoryRoutes);
router.use("/water-sources", waterSourceRoutes);
router.use("/map", mapRoutes);
router.use("/ndvi", ndviRouter);
router.use("/rainfall", rainfallRouter);
router.use("/groundwater", groundwaterRouter);
router.use("/weather", weatherRoutes);
router.use("/reports", reportRoutes);
router.use("/tenants", tenantRoutes);
router.use("/uploads", uploadRoutes);
router.use("/provider/sensors", providerSensorRoutes);
router.use("/settings", settingsRoutes);
router.use("/aois", aoiRoutes);

export default router;
